<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="coverlet.MTP" />
    <PackageReference Include="EnyimMemcachedCore" />
    <PackageReference Include="FakeItEasy" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="StackExchange.Redis" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\testconfig.json" Link="testconfig.json" TargetPath="$(AssemblyName).testconfig.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Carter.Cache.Memcached\Carter.Cache.Memcached.csproj" />
    <ProjectReference Include="..\..\src\Carter.Cache.Redis\Carter.Cache.Redis.csproj" />
    <ProjectReference Include="..\..\src\Carter.Cache\Carter.Cache.csproj" />
  </ItemGroup>
</Project>
