version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/samples/Sample.Carter.Cache.Application" #Sample.Carter.Cache.Application.csproj
    schedule:
      interval: "weekly"
      day: "friday"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
  - package-ecosystem: "nuget"
    directory: "/samples/Sample.Carter.Cache.Memcached.Application" #Sample.Carter.Cache.Memcached.Application.csproj
    schedule:
      interval: "weekly"
      day: "friday"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
  - package-ecosystem: "nuget"
    directory: "/src/Carter.Cache" #Carter.Cache.csproj
    schedule:
      interval: "weekly"
      day: "friday"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
  - package-ecosystem: "nuget"
    directory: "/src/Carter.Cache.Memcached" #Carter.Cache.Memcached.csproj
    schedule:
      interval: "weekly"
      day: "friday"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
  - package-ecosystem: "nuget"
    directory: "/tests/Carter.Cache.Tests" #Carter.Cache.Tests.csproj
    schedule:
      interval: "weekly"
      day: "friday"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
  - package-ecosystem: "nuget"
    directory: "/tests/Carter.Cache.Sample.Tests" #Carter.Cache.Sample.Tests.csproj
    schedule:
      interval: "weekly"
      day: "friday"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
  - package-ecosystem: "nuget"
    directory: "/tests/Carter.Cache.Sample.Memcached.Tests" #Carter.Cache.Sample.Memcached.Tests.csproj
    schedule:
      interval: "weekly"
      day: "friday"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"


