<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="coverlet.MTP" Version="10.0.1" />
    <PackageVersion Include="FakeItEasy" Version="9.0.0" />
    <PackageVersion Include="EnyimMemcachedCore" Version="3.5.1" />
    <PackageVersion Include="Microsoft.Extensions.Caching.Memory" Version="10.0.12" />
    <PackageVersion Include="StackExchange.Redis" Version="2.9.32" />
    <PackageVersion Include="System.Text.Json" Version="10.0.12" />
    <PackageVersion Include="Carter" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.401" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageVersion Include="Scalar.AspNetCore" Version="2.17.3" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Testing.Platform" Version="2.4.0" />
    <PackageVersion Include="MessagePack" Version="3.1.7" />
    <PackageVersion Include="xunit.v3" Version="4.0.0" />
  </ItemGroup>
</Project>