<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>A memcached plugin for the carter caching library</Description>
    <PackageTags>carter cache memcached</PackageTags>
    <PackageReleaseNotes>Addition of target: .NET 10</PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EnyimMemcachedCore" />
    <PackageReference Include="MessagePack" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Carter.Cache\Carter.Cache.csproj" />
  </ItemGroup>

</Project>
