name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Run dependency images
      run: docker-compose -f docker/docker-compose.yml up -d
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal /p:AltCover=true /p:AltCoverAssemblyExcludeFilter="xunit"
    - name: Codecov
      uses: codecov/codecov-action@v1.2.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: tests/Carter.Cache.Tests/coverage.xml
    - name: Pack
      run: dotnet pack src/Carter.Cache/Carter.Cache.csproj -o $NUPKGS --include-symbols
    - name: Pack Memcached
      run: dotnet pack src/Carter.Cache.Memcached/Carter.Cache.Memcached.csproj -o $NUPKGS --include-symbols
    - name: Pack Redis
      run: dotnet pack src/Carter.Cache.Redis/Carter.Cache.Redis.csproj -o $NUPKGS --include-symbols
    - name: Publish Myget
      run: dotnet nuget push "$NUPKGS/*.nupkg" --skip-duplicate --source $MYGET_FEED -k ${{ secrets.MYGET_KEY }}
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  MYGET_FEED: https://www.myget.org/F/carter-cache/api/v3/index.json
  NUPKGS: ./.nupkgs
