name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack src/Carter.Cache/Carter.Cache.csproj -o $NUPKGS --include-symbols
    - name: Publish Feedz
      run: |
          for f in $NUPKGS/*.nupkg
          do
            dotnet nuget push $f --source $FEEDZ_FEED -k  ${{ secrets.FEEDZ_KEY }}
          done
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  FEEDZ_FEED: https://f.feedz.io/jaxelr/carter-cache/nuget/index.json
  NUPKGS: ./.nupkgs
